teleported-spawn: "Teleported to spawn!"
set-spawn: "Set spawn at your location!"
teleported-checkpoint: "Teleported to last"
set-checkpoint: "Checkpoint!"
no-checkpoint: "You have no checkpoint yet!"
player-finished-first: "You finished and your time was "
player-finished-better: ". Which i better than your last attempt!"
player-finished-worse: ". However this was not your fastest attempt."
race-not-started: "You have not started the race!"