name: Race
version: '1.0-SNAPSHOT'
main: net.derfla.race.Race
api-version: 1.20
author: AffeKri
commands:
  spawn:
    usage: /<command>
    permission: race.race
    permission-message: You do not have <permission>
  race:
    usage: /<command>
    permission: race.race
    permission-message: You do not have <permission>
  checkpoint:
    usage: /<command>
    permission: race.race
    permission-message: You do not have <permission>
